language: node_js

node_js:
  - v12

addons:
  code_climate:

env:
  NODE_ENV: 'test'

notifications:
  email:
    - alberto@wejs.org

after_success:
- npm install coveralls
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js